export const appLayoutStyles = {
  shell: 'min-h-screen overflow-x-clip bg-[radial-gradient(circle_at_top_left,rgba(102,126,234,0.16),transparent_0_28%),radial-gradient(circle_at_bottom_right,rgba(15,118,110,0.12),transparent_0_24%),linear-gradient(180deg,rgb(var(--background)),rgb(var(--background)))] text-foreground',
  skipLink: 'sr-only fixed left-4 top-4 z-50 rounded-full bg-foreground px-4 py-2 text-sm font-medium text-background focus:not-sr-only focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2',
  frame: 'relative min-h-screen lg:grid lg:grid-cols-[auto_minmax(0,1fr)]',
  backdrop: 'fixed inset-0 z-30 bg-slate-950/35 backdrop-blur-sm lg:hidden',
  sidebar: 'fixed inset-y-0 left-0 z-40 flex w-[17.5rem] flex-col border-r border-sidebar-border bg-sidebar/92 shadow-[0_24px_60px_-32px_rgba(15,23,42,0.38)] backdrop-blur-xl transition-[width,transform] duration-200 lg:sticky lg:top-0 lg:h-screen lg:translate-x-0',
  sidebarOpen: 'translate-x-0',
  sidebarClosed: '-translate-x-full lg:translate-x-0',
  sidebarExpanded: 'lg:w-[17.5rem]',
  sidebarCollapsed: 'lg:w-[5.5rem]',
  sidebarInner: 'flex h-full flex-col gap-6 p-3',
  sidebarTop: 'flex items-start justify-between gap-3 rounded-[1.6rem] border border-sidebar-border/80 bg-panel/70 px-3 py-4',
  brand: 'flex items-center gap-3 min-w-0',
  brandCollapsed: 'justify-center',
  brandMark: 'flex h-11 w-11 items-center justify-center rounded-2xl bg-accent text-accent-foreground shadow-[0_18px_42px_-24px_rgba(15,23,42,0.48)]',
  brandName: 'text-[1.1rem] font-semibold tracking-tight text-foreground',
  brandDescription: 'text-sm text-sidebar-foreground',
  sidebarCollapseButton: 'hidden h-11 w-11 shrink-0 items-center justify-center rounded-2xl border border-border/70 bg-background/70 text-muted-foreground transition hover:text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring lg:inline-flex',
  sidebarBody: 'flex flex-1 flex-col justify-between gap-6 rounded-[1.6rem] border border-sidebar-border/80 bg-panel/66 p-3',
  primaryAction: 'inline-flex min-h-12 items-center justify-center gap-3 rounded-2xl bg-accent px-4 text-sm font-semibold text-accent-foreground shadow-[0_22px_48px_-30px_rgba(15,23,42,0.44)] transition hover:opacity-95 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring',
  primaryActionCollapsed: 'px-0',
  sidebarFooter: 'grid gap-3 rounded-[1.6rem] border border-sidebar-border/80 bg-panel/66 p-3',
  themePanel: 'grid gap-3 rounded-2xl border border-border/70 bg-background/70 p-3',
  themePanelCollapsed: 'justify-items-center p-2',
  themeCopy: 'grid gap-1',
  themeLabel: 'text-xs font-semibold uppercase tracking-[0.22em] text-muted-foreground',
  themeDescription: 'text-xs leading-5 text-muted-foreground',
  themeControls: 'grid grid-cols-2 gap-2',
  themeControlsCollapsed: 'grid-cols-1',
  themeButton: 'inline-flex min-h-11 items-center justify-center gap-2 rounded-2xl border border-border/70 bg-background/80 px-3 text-xs font-semibold text-muted-foreground transition hover:text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring',
  themeButtonActive: 'border-accent/15 bg-accent text-accent-foreground shadow-[0_18px_40px_-24px_rgba(15,23,42,0.48)]',
  secondaryActions: 'grid gap-1',
  secondaryAction: 'inline-flex min-h-11 items-center gap-3 rounded-2xl px-3 text-sm font-medium text-sidebar-foreground transition hover:bg-background/70 hover:text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring',
  secondaryActionCollapsed: 'justify-center px-0',
  mainColumn: 'flex min-w-0 flex-1 flex-col',
  topBar: 'sticky top-0 z-20 border-b border-border/70 bg-panel/84 backdrop-blur-xl',
  topBarContent: 'flex min-h-[5.5rem] w-full items-center gap-3 px-4 sm:px-6 xl:px-8 2xl:px-10',
  headerLeft: 'flex min-w-0 items-center gap-3',
  mobileMenuButton: 'inline-flex h-11 w-11 items-center justify-center rounded-2xl border border-border/70 bg-background/78 text-muted-foreground transition hover:text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring lg:hidden',
  headerMetric: 'hidden min-w-[12rem] rounded-2xl border border-border/70 bg-background/75 px-4 py-3 md:block',
  headerMetricLabel: 'text-sm font-semibold text-foreground',
  headerRight: 'ml-auto flex items-center gap-2',
  searchField: 'hidden min-w-[17rem] items-center gap-2 rounded-full border border-border/70 bg-background/78 px-4 py-2 text-sm text-muted-foreground shadow-sm lg:flex xl:min-w-[22rem]',
  searchInput: 'w-full border-0 bg-transparent text-sm text-foreground outline-none placeholder:text-muted-foreground',
  iconButton: 'inline-flex h-11 w-11 items-center justify-center rounded-full border border-border/70 bg-background/78 text-muted-foreground transition hover:text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring',
  iconButtonMobileOnly: 'inline-flex h-11 w-11 items-center justify-center rounded-full border border-border/70 bg-background/78 text-muted-foreground transition hover:text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring lg:hidden',
  statusRow: 'flex flex-col gap-2 px-4 py-4 sm:px-6 xl:flex-row xl:items-center xl:justify-between xl:px-8 2xl:px-10',
  status: 'inline-flex self-start items-center rounded-full bg-panel px-3 py-1 text-xs font-medium uppercase tracking-[0.2em] text-muted-foreground shadow-[0_12px_30px_-18px_rgba(15,23,42,0.35)]',
  statusHint: 'text-sm text-muted-foreground',
  content: 'flex min-w-0 flex-1 flex-col px-4 pb-10 pt-2 sm:px-6 xl:px-8 2xl:px-10',
};