export const notificationsSettingsWorkspaceStyles = {
  container: 'mx-auto grid max-w-5xl gap-6',
  cardStack: 'grid gap-6 lg:grid-cols-[minmax(0,1.2fr)_minmax(0,0.8fr)]',
  form: 'grid gap-4',
  formGrid: 'grid gap-4 md:grid-cols-2',
  field: 'grid gap-2',
  fieldWide: 'grid gap-2 md:col-span-2',
  label: 'text-[11px] font-semibold uppercase tracking-[0.18em] text-muted-foreground',
  value: 'mt-1 text-sm font-medium text-foreground',
  input: 'h-11 rounded-[1rem] border border-border/70 bg-background px-4 text-sm text-foreground shadow-sm outline-none transition focus:border-cyan-500 focus:ring-2 focus:ring-cyan-200 disabled:cursor-not-allowed disabled:opacity-60',
  checkboxRow: 'flex items-start justify-between gap-4 rounded-[1.25rem] border border-border/60 bg-background/80 px-4 py-4',
  checkboxLabelWrap: 'grid gap-1',
  checkbox: 'mt-1 h-4 w-4 rounded border-border text-cyan-700 focus:ring-cyan-200',
  helper: 'text-sm leading-6 text-muted-foreground',
  error: 'text-sm font-medium text-rose-600',
  actions: 'flex flex-wrap items-center gap-3',
  statusGrid: 'grid gap-3 sm:grid-cols-2',
  statusCard: 'rounded-[1.25rem] border border-border/60 bg-background/80 px-4 py-4',
  statusLabel: 'text-[11px] font-semibold uppercase tracking-[0.18em] text-muted-foreground',
  statusValue: 'mt-2 text-sm font-semibold text-foreground',
  previewCard: 'grid gap-3 rounded-[1.5rem] border border-border/60 bg-background/70 p-4',
  previewTitle: 'text-sm font-semibold text-foreground',
  previewText: 'text-sm leading-6 text-muted-foreground',
  historyList: 'grid gap-3',
  historyItem: 'rounded-[1.25rem] border border-border/60 bg-background/80 px-4 py-4',
  historyMeta: 'mt-1 text-xs font-medium uppercase tracking-[0.14em] text-muted-foreground',
};