export const projectFormStyles = {
  form: 'grid gap-5',
  grid: 'grid gap-4 md:grid-cols-2',
  field: 'grid gap-2',
  label: 'text-sm font-medium text-foreground',
  input: 'min-h-11 rounded-2xl border border-border/70 bg-background px-4 text-sm text-foreground outline-none transition focus:border-foreground/40 focus:ring-2 focus:ring-ring/15',
  select: 'min-h-11 rounded-2xl border border-border/70 bg-background px-4 text-sm text-foreground outline-none transition focus:border-foreground/40 focus:ring-2 focus:ring-ring/15',
  helper: 'text-xs leading-5 text-muted-foreground',
  error: 'text-xs leading-5 text-rose-700',
  switchGroup: 'grid gap-3 md:grid-cols-2',
  switchCard: 'rounded-2xl border border-border/70 bg-background p-4',
  switchLabel: 'text-sm font-medium text-foreground',
  days: 'flex flex-wrap gap-2',
  dayButton: 'inline-flex min-h-10 items-center rounded-full border border-border/70 bg-background px-3 text-xs font-medium uppercase tracking-[0.18em] text-muted-foreground transition hover:border-foreground/30 hover:text-foreground',
  dayButtonActive: 'border-transparent bg-foreground text-background hover:bg-foreground hover:text-background',
  footer: 'flex flex-col gap-3 border-t border-border/60 pt-5 md:flex-row md:items-center md:justify-between',
  footerText: 'text-sm leading-6 text-muted-foreground',
  actions: 'flex flex-wrap gap-3',
};