export const cycleTasksBoardStyles = {
  wrapper: 'grid gap-5',
  helper: 'text-sm leading-6 text-muted-foreground',
  empty: 'grid gap-4 rounded-[1.5rem] border border-dashed border-border/70 bg-background/45 px-5 py-6 text-sm leading-6 text-muted-foreground md:grid-cols-[1fr_auto] md:items-center',
  board: 'grid gap-4 xl:grid-cols-3',
  column: 'grid gap-4 rounded-[1.5rem] border border-border/60 bg-muted/25 p-4',
  columnHeader: 'flex items-start justify-between gap-3',
  columnMeta: 'grid gap-1',
  columnTitle: 'text-base font-semibold tracking-tight text-foreground',
  columnCount: 'text-[11px] font-semibold uppercase tracking-[0.18em] text-muted-foreground',
  columnTone: 'inline-flex min-h-8 items-center rounded-full bg-background px-3 text-[11px] font-semibold uppercase tracking-[0.18em] text-foreground/70',
  columnList: 'grid gap-3',
  card: 'grid gap-4 rounded-[1.25rem] border border-border/70 bg-background/95 p-4 shadow-[0_16px_45px_-32px_rgba(15,23,42,0.3)]',
  cardTitle: 'text-sm font-semibold tracking-tight text-foreground',
  cardMeta: 'text-sm leading-6 text-muted-foreground',
  cardFooter: 'flex flex-wrap items-center gap-2',
  badge: 'inline-flex min-h-7 items-center rounded-full px-2.5 text-[10px] font-semibold uppercase tracking-[0.16em]',
  selectWrap: 'grid gap-2',
  selectLabel: 'text-[11px] font-semibold uppercase tracking-[0.18em] text-muted-foreground',
  select: 'min-h-10 rounded-2xl border border-border/70 bg-background px-3 text-sm text-foreground outline-none transition focus:border-foreground/40 focus:ring-2 focus:ring-ring/15',
  skipButton: 'h-auto justify-start px-0 text-sm font-medium text-foreground/80 underline underline-offset-4 hover:text-foreground',
  skipConfirm: 'grid gap-3 rounded-2xl border border-border/60 bg-muted/35 p-3',
  skipConfirmCopy: 'text-sm leading-6 text-muted-foreground',
  skipConfirmActions: 'flex flex-wrap gap-2',
  critical: 'bg-rose-100 text-rose-800',
  high: 'bg-amber-100 text-amber-800',
  medium: 'bg-slate-200 text-slate-700',
  low: 'bg-emerald-100 text-emerald-800',
  backlogTone: 'bg-slate-200 text-slate-700',
  inProgressTone: 'bg-sky-100 text-sky-800',
  doneTone: 'bg-emerald-100 text-emerald-800',
};