export const cycleTasksBoardStyles = {
  wrapper: 'grid gap-5',
  helper: 'text-sm leading-6 text-muted-foreground',
  menuBackdrop: 'fixed inset-0 z-10 cursor-default',
  empty: 'grid gap-4 rounded-[1.5rem] border border-dashed border-border/70 bg-background/45 px-5 py-6 text-sm leading-6 text-muted-foreground md:grid-cols-[1fr_auto] md:items-center',
  board: 'grid gap-4 xl:grid-cols-3',
  column: 'grid gap-4 rounded-[1.5rem] border border-border/60 bg-muted/25 p-4',
  columnHeader: 'flex items-start justify-between gap-3',
  columnMeta: 'grid gap-1',
  columnTitle: 'text-base font-semibold tracking-tight text-foreground',
  columnCount: 'text-[11px] font-semibold uppercase tracking-[0.18em] text-muted-foreground',
  columnTone: 'inline-flex min-h-8 items-center rounded-full bg-background px-3 text-[11px] font-semibold uppercase tracking-[0.18em] text-foreground/70',
  columnList: 'grid gap-3',
  columnListDropTarget: 'rounded-[1rem] bg-sky-50/70 p-2 ring-2 ring-sky-200',
  columnEmpty: 'rounded-[1rem] border border-dashed border-border/70 bg-background/80 px-4 py-5 text-sm leading-6 text-muted-foreground',
  card: 'grid gap-4 rounded-[1.25rem] border border-border/70 bg-background/95 p-4 shadow-[0_16px_45px_-32px_rgba(15,23,42,0.3)] transition',
  cardDragging: 'cursor-grabbing opacity-60',
  cardDropTarget: 'ring-2 ring-sky-300',
  cardTop: 'flex items-start justify-between gap-3',
  cardBody: 'grid gap-1',
  cardTitle: 'text-sm font-semibold tracking-tight text-foreground',
  cardMeta: 'text-sm leading-6 text-muted-foreground',
  cardDescription: 'text-sm leading-6 text-muted-foreground [display:-webkit-box] [-webkit-box-orient:vertical] [-webkit-line-clamp:3] overflow-hidden',
  cardFooter: 'flex flex-wrap items-center gap-2',
  checklistBadge: 'inline-flex min-h-7 items-center gap-1.5 rounded-full bg-muted px-2.5 text-[10px] font-semibold uppercase tracking-[0.16em] text-foreground/72',
  badge: 'inline-flex min-h-7 items-center rounded-full px-2.5 text-[10px] font-semibold uppercase tracking-[0.16em]',
  cardActionsWrap: 'relative z-20',
  cardActionsButton: 'inline-flex h-9 w-9 items-center justify-center rounded-full border border-border/60 bg-background/85 text-foreground/72 transition hover:text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring',
  menu: 'absolute right-0 top-11 z-30 grid min-w-[14rem] gap-1 rounded-[1.25rem] border border-border/70 bg-card p-2 shadow-[0_24px_80px_-36px_rgba(15,23,42,0.42)]',
  menuLabel: 'px-3 pt-2 text-[11px] font-semibold uppercase tracking-[0.18em] text-muted-foreground',
  menuAction: 'inline-flex min-h-10 items-center rounded-2xl px-3 text-left text-sm font-medium text-foreground/82 transition hover:bg-muted hover:text-foreground disabled:cursor-not-allowed disabled:opacity-50',
  skipConfirm: 'grid gap-3 rounded-2xl border border-border/60 bg-muted/35 p-3',
  skipConfirmCopy: 'text-sm leading-6 text-muted-foreground',
  skipConfirmActions: 'flex flex-wrap gap-2',
  critical: 'bg-rose-100 text-rose-800',
  high: 'bg-amber-100 text-amber-800',
  medium: 'bg-slate-200 text-slate-700',
  low: 'bg-emerald-100 text-emerald-800',
  backlogTone: 'bg-slate-200 text-slate-700',
  inProgressTone: 'bg-sky-100 text-sky-800',
  doneTone: 'bg-emerald-100 text-emerald-800',
};