export const cycleTasksBoardStyles = {
  wrapper: 'grid gap-4',
  summary: 'grid gap-4 md:grid-cols-3',
  summaryItem: 'rounded-2xl bg-background/72 px-4 py-4',
  summaryLabel: 'text-[11px] font-medium uppercase tracking-[0.18em] text-muted-foreground',
  summaryValue: 'mt-2 text-lg font-semibold text-foreground',
  list: 'grid gap-3',
  item: 'rounded-2xl border border-border/60 bg-background/78 px-4 py-4',
  itemOverflow: 'border-amber-300/70 bg-amber-50/70 dark:bg-amber-950/30',
  top: 'flex flex-col gap-3 md:flex-row md:items-start md:justify-between',
  title: 'text-base font-semibold text-foreground',
  copy: 'mt-1 text-sm leading-6 text-muted-foreground',
  meta: 'mt-3 flex flex-wrap gap-2',
  badge: 'inline-flex min-h-9 items-center rounded-full px-3 text-xs font-medium',
  badgeFit: 'bg-emerald-100 text-emerald-800',
  badgeOverflow: 'bg-amber-100 text-amber-900',
  badgeProject: 'bg-slate-200 text-slate-700 dark:bg-slate-800 dark:text-slate-200',
  actions: 'mt-4 flex flex-wrap gap-3',
  empty: 'rounded-2xl border border-dashed border-border/70 bg-background/65 px-4 py-5 text-sm leading-6 text-muted-foreground',
};