export const tasksListStyles = {
  board: 'grid gap-5',
  boardHeader: 'flex items-center justify-between gap-4',
  boardCopy: 'grid gap-2',
  boardTitle: 'text-xl font-semibold tracking-tight text-foreground',
  boardDescription: 'hidden text-sm leading-6 text-muted-foreground md:block',
  boardScroller: 'overflow-x-auto pb-2 [-ms-overflow-style:none] [scrollbar-width:none] [&::-webkit-scrollbar]:hidden',
  boardColumns: 'flex min-w-max gap-4',
  column: 'flex w-[20rem] shrink-0 flex-col rounded-[1.7rem] border border-border/60 bg-card/92 p-4 shadow-[0_18px_55px_-30px_rgba(15,23,42,0.24)]',
  columnHeader: 'flex items-start justify-between gap-3',
  columnActions: 'flex items-center gap-2',
  columnMeta: 'grid gap-1',
  columnTitle: 'text-base font-semibold tracking-tight text-foreground',
  columnCount: 'text-xs uppercase tracking-[0.18em] text-muted-foreground',
  columnTone: 'inline-flex min-h-8 items-center rounded-full bg-muted/50 px-3 text-[11px] font-semibold uppercase tracking-[0.18em] text-foreground/72',
  columnRemoveButton: 'inline-flex h-8 w-8 items-center justify-center rounded-full border border-border/60 bg-background/75 text-foreground/70 transition hover:text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring',
  columnList: 'mt-4 grid gap-3',
  columnEmpty: 'rounded-2xl border border-dashed border-border/70 bg-background/45 px-4 py-5 text-sm leading-6 text-muted-foreground',
  item: 'rounded-[1.25rem] border border-border/55 bg-background/90 p-4 shadow-[0_16px_45px_-30px_rgba(15,23,42,0.3)]',
  top: 'flex items-start justify-between gap-3',
  body: 'grid gap-2',
  menuWrap: 'relative',
  menuButton: 'inline-flex h-9 w-9 shrink-0 items-center justify-center rounded-full border border-border/60 bg-background/78 text-foreground/78 transition hover:text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring',
  menu: 'absolute right-0 top-11 z-20 grid min-w-[15rem] gap-1 rounded-[1.25rem] border border-border/70 bg-card p-2 shadow-[0_24px_80px_-36px_rgba(15,23,42,0.42)]',
  menuLabel: 'px-3 pt-2 text-[11px] font-semibold uppercase tracking-[0.18em] text-muted-foreground',
  menuAction: 'inline-flex min-h-10 items-center rounded-2xl px-3 text-sm font-medium text-foreground/82 transition hover:bg-muted hover:text-foreground',
  menuActionDanger: 'text-rose-700 hover:bg-rose-50 hover:text-rose-800 dark:hover:bg-rose-950/30',
  menuSelect: 'min-h-10 rounded-2xl border border-border/70 bg-background px-3 text-sm text-foreground outline-none transition focus:border-foreground/40 focus:ring-2 focus:ring-ring/15',
  title: 'text-base font-semibold tracking-tight text-foreground',
  meta: 'mt-1 text-sm leading-6 text-muted-foreground',
  description: 'text-sm leading-6 text-muted-foreground [display:-webkit-box] [-webkit-box-orient:vertical] [-webkit-line-clamp:2] overflow-hidden',
  checklistSummary: 'text-[11px] font-semibold uppercase tracking-[0.15em] text-muted-foreground',
  chips: 'mt-2 flex flex-wrap gap-2',
  chip: 'inline-flex min-h-7 items-center rounded-full px-2.5 text-[10px] font-semibold uppercase tracking-[0.16em]',
  footer: 'mt-4 grid gap-2 border-t border-border/60 pt-4',
  footerText: 'text-sm text-muted-foreground',
  moveSelect: 'min-h-10 rounded-2xl border border-border/70 bg-background px-3 text-sm text-foreground outline-none transition focus:border-foreground/40 focus:ring-2 focus:ring-ring/15',
  actions: 'flex flex-wrap gap-3',
  addColumnPanel: 'w-[20rem] shrink-0 rounded-[1.7rem] border border-dashed border-border/70 bg-background/40 p-4',
  addColumnForm: 'grid gap-3',
  addColumnInput: 'min-h-11 rounded-2xl border border-border/70 bg-background px-4 text-sm text-foreground outline-none transition focus:border-foreground/40 focus:ring-2 focus:ring-ring/15',
  addColumnHint: 'text-sm leading-6 text-muted-foreground',
  critical: 'bg-rose-100 text-rose-800',
  high: 'bg-amber-100 text-amber-800',
  medium: 'bg-slate-200 text-slate-700',
  low: 'bg-emerald-100 text-emerald-800',
  overdue: 'bg-rose-100 text-rose-800',
  today: 'bg-orange-100 text-orange-800',
  soon: 'bg-sky-100 text-sky-800',
  planned: 'bg-slate-200 text-slate-700',
  todo: 'bg-slate-200 text-slate-700',
  doing: 'bg-sky-100 text-sky-800',
  blocked: 'bg-fuchsia-100 text-fuchsia-800',
  done: 'bg-emerald-100 text-emerald-800',
  cycleChip: 'bg-indigo-100 text-indigo-800',
};