export const tasksListStyles = {
  board: 'grid gap-5',
  boardHeader: 'flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between',
  boardCopy: 'grid gap-2',
  boardTitle: 'text-lg font-semibold tracking-tight text-foreground',
  boardDescription: 'text-sm leading-6 text-muted-foreground',
  boardScroller: 'overflow-x-auto pb-2 [-ms-overflow-style:none] [scrollbar-width:none] [&::-webkit-scrollbar]:hidden',
  boardColumns: 'flex min-w-max gap-4',
  column: 'flex w-[20rem] shrink-0 flex-col rounded-[1.7rem] border border-border/60 bg-card/92 p-4 shadow-[0_18px_55px_-30px_rgba(15,23,42,0.24)]',
  columnHeader: 'flex items-start justify-between gap-3',
  columnMeta: 'grid gap-1',
  columnTitle: 'text-base font-semibold tracking-tight text-foreground',
  columnCount: 'text-xs uppercase tracking-[0.18em] text-muted-foreground',
  columnTone: 'inline-flex min-h-8 items-center rounded-full bg-muted/50 px-3 text-[11px] font-semibold uppercase tracking-[0.18em] text-foreground/72',
  columnList: 'mt-4 grid gap-3',
  columnEmpty: 'rounded-2xl border border-dashed border-border/70 bg-background/45 px-4 py-5 text-sm leading-6 text-muted-foreground',
  item: 'rounded-[1.25rem] border border-border/55 bg-background/90 p-4 shadow-[0_16px_45px_-30px_rgba(15,23,42,0.3)]',
  top: 'flex flex-col gap-3',
  title: 'text-base font-semibold tracking-tight text-foreground',
  meta: 'mt-1 text-sm leading-6 text-muted-foreground',
  chips: 'mt-3 flex flex-wrap gap-2',
  chip: 'inline-flex min-h-10 items-center rounded-full px-3 text-xs font-medium uppercase tracking-[0.18em]',
  footer: 'mt-4 grid gap-3 border-t border-border/60 pt-4',
  footerTop: 'grid gap-2',
  footerBottom: 'flex flex-wrap gap-2',
  footerLabel: 'text-[11px] font-medium uppercase tracking-[0.18em] text-muted-foreground',
  footerText: 'text-sm text-muted-foreground',
  moveSelect: 'min-h-10 rounded-2xl border border-border/70 bg-background px-3 text-sm text-foreground outline-none transition focus:border-foreground/40 focus:ring-2 focus:ring-ring/15',
  actions: 'flex flex-wrap gap-3',
  addColumnPanel: 'w-[20rem] shrink-0 rounded-[1.7rem] border border-dashed border-border/70 bg-background/40 p-4',
  addColumnForm: 'grid gap-3',
  addColumnInput: 'min-h-11 rounded-2xl border border-border/70 bg-background px-4 text-sm text-foreground outline-none transition focus:border-foreground/40 focus:ring-2 focus:ring-ring/15',
  addColumnHint: 'text-sm leading-6 text-muted-foreground',
  critical: 'bg-rose-100 text-rose-800',
  high: 'bg-amber-100 text-amber-800',
  medium: 'bg-slate-200 text-slate-700',
  low: 'bg-emerald-100 text-emerald-800',
  overdue: 'bg-rose-100 text-rose-800',
  today: 'bg-orange-100 text-orange-800',
  soon: 'bg-sky-100 text-sky-800',
  planned: 'bg-slate-200 text-slate-700',
  todo: 'bg-slate-200 text-slate-700',
  doing: 'bg-sky-100 text-sky-800',
  blocked: 'bg-fuchsia-100 text-fuchsia-800',
  done: 'bg-emerald-100 text-emerald-800',
  cycleChip: 'bg-indigo-100 text-indigo-800',
};