export const tasksListStyles = {
  list: 'grid gap-4',
  item: 'rounded-[1.5rem] border border-border/60 bg-card/90 p-5 shadow-[0_18px_55px_-30px_rgba(15,23,42,0.28)]',
  top: 'flex flex-col gap-4 md:flex-row md:items-start md:justify-between',
  title: 'text-lg font-semibold tracking-tight text-foreground',
  meta: 'mt-2 text-sm leading-6 text-muted-foreground',
  chips: 'mt-4 flex flex-wrap gap-2',
  chip: 'inline-flex min-h-10 items-center rounded-full px-3 text-xs font-medium uppercase tracking-[0.18em]',
  footer: 'mt-5 flex flex-wrap items-center justify-between gap-3 border-t border-border/60 pt-4',
  footerText: 'text-sm text-muted-foreground',
  actions: 'flex flex-wrap gap-3',
  critical: 'bg-rose-100 text-rose-800',
  high: 'bg-amber-100 text-amber-800',
  medium: 'bg-slate-200 text-slate-700',
  low: 'bg-emerald-100 text-emerald-800',
  overdue: 'bg-rose-100 text-rose-800',
  today: 'bg-orange-100 text-orange-800',
  soon: 'bg-sky-100 text-sky-800',
  planned: 'bg-slate-200 text-slate-700',
  todo: 'bg-slate-200 text-slate-700',
  doing: 'bg-sky-100 text-sky-800',
  blocked: 'bg-fuchsia-100 text-fuchsia-800',
  done: 'bg-emerald-100 text-emerald-800',
};