export const dashboardWorkspaceStyles = {
  layout: 'grid gap-6',
  headerStack: 'grid gap-4',
  hero: 'grid gap-4 overflow-hidden rounded-[2rem] border border-border/60 bg-[radial-gradient(circle_at_top_left,rgba(14,165,233,0.12),transparent_32%),radial-gradient(circle_at_bottom_right,rgba(15,23,42,0.09),transparent_28%)] p-6 shadow-[0_22px_70px_-34px_rgba(15,23,42,0.32)] lg:grid-cols-[1.15fr_0.85fr] lg:items-start',
  heroCopy: 'grid gap-5',
  heroActions: 'flex flex-col gap-3 sm:flex-row',
  heroNotice: 'grid content-start',
  contextGrid: 'grid gap-4 xl:grid-cols-3',
  contextCard: 'h-full',
  contextHighlights: 'grid gap-2 pt-2',
  contextHighlight: 'rounded-2xl bg-background/70 px-4 py-3 text-sm text-foreground',
  signalRail: 'flex flex-wrap gap-2 text-xs text-muted-foreground',
  signalChip: 'rounded-full border border-border/60 bg-card/85 px-3 py-1.5 shadow-[0_10px_26px_-20px_rgba(15,23,42,0.45)]',
  summaryGrid: 'grid gap-4 md:grid-cols-3',
  metricValue: 'text-3xl font-semibold tracking-tight text-foreground',
  sectionStack: 'grid gap-4',
  sectionHeader: 'flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between',
  sectionCopy: 'max-w-2xl text-sm leading-6 text-muted-foreground',
  compactTable: 'overflow-x-auto rounded-[1.75rem] border border-border/60 bg-card/90 shadow-[0_18px_55px_-30px_rgba(15,23,42,0.28)]',
  compactTableRow: 'grid min-w-[44rem] grid-cols-[1.2fr_0.8fr_0.8fr_0.8fr_0.7fr] items-center gap-3 px-4 py-4 text-sm sm:px-5',
  compactTableHeader: 'bg-muted/45 text-[11px] font-medium uppercase tracking-[0.18em] text-muted-foreground',
  compactTableAlt: 'bg-background/70',
  projectCell: 'flex items-center gap-3 font-medium text-foreground',
  projectDot: 'h-3.5 w-3.5 rounded-full',
  numericCell: 'text-sm text-foreground',
  mutedCell: 'text-sm text-muted-foreground',
  status: 'inline-flex rounded-full px-2.5 py-1 text-xs font-medium',
  statusBalanced: 'bg-emerald-100 text-emerald-800',
  statusAttention: 'bg-amber-100 text-amber-800',
  statusCritical: 'bg-rose-100 text-rose-800',
  lowerGrid: 'grid gap-4 xl:grid-cols-[1.15fr_0.85fr]',
  loadGrid: 'grid gap-3',
  loadItem: 'flex flex-col gap-3 rounded-2xl bg-background/70 px-4 py-3 sm:flex-row sm:items-center sm:justify-between',
  loadMeta: 'flex items-center gap-3',
  loadName: 'text-sm font-medium text-foreground',
  loadCopy: 'mt-1 text-xs text-muted-foreground',
  loadEffort: 'text-right',
  loadEffortHours: 'text-base font-semibold tracking-tight text-foreground',
  loadEffortScore: 'mt-1 text-xs text-muted-foreground',
  riskHeader: 'flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between',
  riskSummaryGrid: 'grid gap-3 md:grid-cols-2',
  riskSummaryItem: 'rounded-2xl border border-border/60 bg-background/75 p-4',
  riskEyebrow: 'text-[11px] uppercase tracking-[0.18em] text-muted-foreground',
  riskTitle: 'mt-2 text-sm font-semibold tracking-tight text-foreground',
  riskDescription: 'mt-2 text-sm leading-6 text-muted-foreground',
  riskDanger: 'border-rose-200/80 bg-rose-50/85',
  riskWarning: 'border-amber-200/80 bg-amber-50/90',
  riskPositive: 'border-emerald-200/80 bg-emerald-50/80',
  riskNeutral: 'border-border/60 bg-background/75',
  riskDetailList: 'grid gap-2 pt-4',
  riskDetailItem: 'rounded-2xl bg-background/80 px-4 py-3 text-sm text-foreground',
  timeTable: 'grid gap-3',
  timeRow: 'grid grid-cols-[1.1fr_0.75fr_0.75fr] items-center gap-3 rounded-2xl bg-background/70 px-4 py-3 min-[460px]:grid-cols-[1.2fr_0.8fr_0.8fr]',
  timeHeader: 'text-[11px] uppercase tracking-[0.18em] text-muted-foreground',
  timeValue: 'text-sm font-medium text-foreground',
};