export const weeklyBalanceWorkspaceStyles = {
  layout: 'grid gap-6',
  summaryGrid: 'grid gap-4 md:grid-cols-4',
  metricValue: 'text-3xl font-semibold tracking-tight text-foreground',
  board: 'overflow-x-auto rounded-[1.75rem] border border-border/60 bg-card/90 shadow-[0_18px_55px_-30px_rgba(15,23,42,0.28)]',
  row: 'grid min-w-[72rem] grid-cols-[1.1fr_repeat(6,minmax(5rem,1fr))_0.8fr_0.8fr_0.8fr_0.8fr] items-center gap-3 px-5 py-4 text-sm',
  rowHeader: 'bg-muted/45 text-[11px] font-medium uppercase tracking-[0.18em] text-muted-foreground',
  rowAlt: 'bg-background/70',
  projectCell: 'flex items-center gap-3 font-medium text-foreground',
  projectColor: 'h-3.5 w-3.5 rounded-full',
  cell: 'text-sm text-foreground',
  mutedCell: 'text-sm text-muted-foreground',
  status: 'text-sm font-medium',
  statusBalanced: 'text-emerald-700',
  statusAttention: 'text-amber-700',
  statusCritical: 'text-rose-700',
  insightGrid: 'grid gap-4 lg:grid-cols-[1.1fr_0.9fr]',
  insightList: 'grid gap-3',
  insightItem: 'flex items-center justify-between gap-4 rounded-2xl bg-background/70 px-4 py-3',
  insightTitle: 'text-sm font-medium text-foreground',
  insightCopy: 'text-xs text-muted-foreground',
};