export const dashboardTimelineChartStyles = {
  container: 'grid gap-5',
  copy: 'text-sm leading-6 text-muted-foreground',
  legend: 'flex flex-wrap gap-3',
  legendItem: 'inline-flex items-center gap-2 rounded-full border border-border/60 bg-background/75 px-3 py-1.5 text-xs font-medium text-foreground',
  legendButton: 'inline-flex items-center gap-2 rounded-full border border-border/60 bg-background/75 px-3 py-1.5 text-xs font-medium text-foreground transition hover:border-sky-300 hover:bg-sky-50/70 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring',
  legendDot: 'h-2.5 w-2.5 rounded-full',
  legendLine: 'h-[2px] w-5 rounded-full bg-slate-900',
  scroller: 'overflow-x-auto pb-2 [-ms-overflow-style:none] [scrollbar-width:none] [&::-webkit-scrollbar]:hidden',
  chartFrame: 'grid gap-3',
  svg: 'h-[220px] w-full rounded-[1.5rem] bg-[linear-gradient(180deg,rgba(248,250,252,0.95),rgba(255,255,255,0.72))] p-2',
  hitArea: 'fill-transparent outline-none focus:fill-sky-100/25',
  totalLine: 'fill-none stroke-slate-900 stroke-[2.5]',
  totalPoint: 'fill-slate-900',
  axis: 'grid auto-cols-[minmax(28px,1fr)] grid-flow-col gap-1',
  axisItem: 'grid gap-1 text-center',
  axisLabel: 'text-[11px] uppercase tracking-[0.14em] text-muted-foreground',
  axisValue: 'text-[11px] text-foreground/78',
  detailPanel: 'grid gap-4 rounded-[1.5rem] border border-border/60 bg-background/80 p-4 shadow-[0_16px_40px_-30px_rgba(15,23,42,0.28)]',
  detailHeader: 'flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between',
  detailEyebrow: 'text-[11px] uppercase tracking-[0.18em] text-muted-foreground',
  detailTitle: 'mt-2 text-lg font-semibold tracking-tight text-foreground',
  detailMetric: 'grid gap-1 rounded-2xl bg-card/80 px-4 py-3 text-sm text-muted-foreground',
  highlightCallout: 'flex flex-col gap-3 rounded-2xl border border-sky-200/70 bg-sky-50/80 px-4 py-3 sm:flex-row sm:items-center sm:justify-between',
  detailGrid: 'grid gap-3 md:grid-cols-2 xl:grid-cols-3',
  detailItem: 'flex items-center justify-between gap-3 rounded-2xl bg-card/80 px-4 py-3',
  detailProjectMeta: 'flex items-center gap-2',
  detailProjectName: 'text-sm font-medium text-foreground',
  detailProjectHours: 'text-sm text-muted-foreground',
};