export const dashboardSuggestionBannerStyles = {
  wrapper: 'grid gap-4 rounded-[1.75rem] border border-border/60 bg-card/90 p-5 shadow-[0_18px_55px_-30px_rgba(15,23,42,0.28)]',
  top: 'flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between',
  eyebrow: 'text-[11px] uppercase tracking-[0.22em] text-muted-foreground',
  title: 'text-lg font-semibold tracking-tight text-foreground',
  description: 'text-sm leading-6 text-muted-foreground',
  list: 'grid gap-3',
  item: 'rounded-2xl bg-background/75 px-4 py-3',
  row: 'flex items-start justify-between gap-3',
  name: 'text-sm font-medium text-foreground',
  copy: 'mt-1 text-xs leading-5 text-muted-foreground',
  positive: 'text-emerald-700',
  negative: 'text-rose-700',
  neutral: 'text-slate-700',
};