export const todayPlannerOverviewStyles = {
  layout: 'grid gap-6 pb-6',
  sessionRail: 'sticky top-24 z-20 grid gap-4',
  sessionBar: 'border-border/70 bg-background/95',
  sessionBarIdle: 'border-2 border-dashed',
  sessionBarRunning: 'border-slate-900 bg-slate-900 text-white',
  sessionBarPaused: 'border-amber-200 bg-amber-50/90',
  sessionBarCompleted: 'border-emerald-200 bg-emerald-50/80',
  sessionBarContent: 'grid gap-4',
  sessionBarHeader: 'flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between',
  sessionEyebrow: 'text-[11px] font-semibold uppercase tracking-[0.18em] text-muted-foreground',
  sessionTitle: 'mt-2 text-2xl font-semibold tracking-tight text-current',
  sessionCopy: 'mt-2 max-w-3xl text-sm leading-6 text-muted-foreground',
  sessionIdleActions: 'flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-end',
  projectPickerRoot: 'relative',
  projectPickerMenu: 'absolute right-0 top-[calc(100%+0.75rem)] z-30 w-[22rem] rounded-3xl border border-border/70 bg-background p-3 shadow-[0_24px_80px_-36px_rgba(15,23,42,0.44)]',
  projectPickerLabel: 'px-2 pb-2 text-[11px] font-semibold uppercase tracking-[0.18em] text-muted-foreground',
  projectPickerList: 'grid gap-2',
  projectPickerItem: 'flex w-full items-center gap-3 rounded-2xl px-3 py-3 text-left transition hover:bg-muted',
  projectPickerItemActive: 'bg-muted',
  projectPickerInfo: 'grid gap-1',
  projectPickerName: 'text-sm font-medium text-foreground',
  projectPickerMeta: 'text-xs text-muted-foreground',
  projectDot: 'h-3 w-3 shrink-0 rounded-full',
  sessionMetrics: 'grid gap-4 sm:grid-cols-3',
  sessionMetric: 'rounded-2xl border border-white/10 bg-white/5 px-4 py-3 backdrop-blur-sm',
  sessionMetricLabel: 'block text-[11px] uppercase tracking-[0.18em] text-current/60',
  sessionMetricValue: 'mt-2 block text-lg font-semibold text-current',
  sessionActions: 'flex flex-wrap gap-3',
  pulseBanner: 'border-sky-200 bg-sky-50/90',
  pulseBannerContent: 'flex flex-col gap-4 md:flex-row md:items-center md:justify-between',
  pulseBannerEyebrow: 'text-[11px] font-semibold uppercase tracking-[0.18em] text-sky-700',
  pulseBannerTitle: 'mt-2 text-lg font-semibold tracking-tight text-sky-950',
  pulseBannerCopy: 'mt-1 text-sm text-sky-800/80',
  cardHeaderInline: 'flex flex-col gap-4 md:flex-row md:items-start md:justify-between',
  planCardContent: 'grid gap-6',
  planList: 'grid gap-3',
  planItem: 'flex items-start justify-between gap-4 rounded-2xl bg-muted/45 px-4 py-4',
  planItemMeta: 'flex items-start gap-3',
  planItemTitle: 'text-sm font-medium text-foreground',
  planItemCopy: 'mt-1 text-xs leading-5 text-muted-foreground',
  planItemHours: 'text-base font-semibold text-foreground',
  collapsedPlanContent: 'flex flex-col gap-4 md:flex-row md:items-center md:justify-between',
  collapsedPlanEyebrow: 'text-[11px] font-semibold uppercase tracking-[0.18em] text-muted-foreground',
  collapsedPlanTitle: 'mt-2 text-lg font-semibold tracking-tight text-foreground',
  activeProjectCard: 'flex flex-col gap-4 md:flex-row md:items-center md:justify-between',
  activeProjectIdentity: 'flex items-center gap-4',
  activeProjectDot: 'h-4 w-4 shrink-0 rounded-full',
  activeProjectLabel: 'text-[11px] font-semibold uppercase tracking-[0.18em] text-muted-foreground',
  activeProjectName: 'mt-2 text-xl font-semibold tracking-tight text-foreground',
  activeProjectCopy: 'text-sm text-muted-foreground',
  progressGrid: 'grid gap-4 lg:grid-cols-3',
  progressBarTrack: 'h-2 rounded-full bg-muted',
  progressBarFill: 'h-2 rounded-full bg-slate-900',
  progressBarFillProject: 'h-2 rounded-full bg-sky-600',
  progressMetaList: 'grid gap-2 text-sm text-muted-foreground',
  positiveText: 'text-emerald-700',
  warningText: 'text-amber-700',
  dangerText: 'text-rose-700',
  drawerStack: 'grid gap-6',
  reviewNotice: 'flex items-start gap-3 rounded-2xl border border-amber-200 bg-amber-50 px-4 py-4 text-sm leading-6 text-amber-900',
  drawerSection: 'grid gap-4',
  drawerSectionHeader: 'grid gap-1',
  drawerSectionTitle: 'text-base font-semibold tracking-tight text-foreground',
  drawerSectionCopy: 'text-sm leading-6 text-muted-foreground',
  drawerList: 'grid gap-3',
  drawerEmptyCopy: 'rounded-2xl bg-muted/45 px-4 py-4 text-sm text-muted-foreground',
  pulseItem: 'flex flex-col gap-4 rounded-2xl border border-border/70 bg-background/80 px-4 py-4 md:flex-row md:items-center md:justify-between',
  pulseItemHighlighted: 'border-sky-300 bg-sky-50/80',
  pulseItemTitle: 'text-sm font-medium text-foreground',
  pulseItemCopy: 'mt-1 text-xs leading-5 text-muted-foreground',
  pulseActions: 'flex flex-wrap gap-2',
  pulseResolutionBadge: 'inline-flex min-h-9 items-center rounded-full bg-muted px-3 text-[11px] font-semibold uppercase tracking-[0.16em] text-muted-foreground',
  timeBlockItem: 'grid gap-4 rounded-2xl border border-border/70 bg-background/80 px-4 py-4',
  timeBlockTop: 'flex flex-col gap-3 md:flex-row md:items-center md:justify-between',
  timeBlockSelect: 'min-h-11 rounded-2xl border border-border/70 bg-background px-4 text-sm text-foreground focus:outline-none focus:ring-2 focus:ring-ring',
  timeBlockWindow: 'text-sm text-muted-foreground',
  timeBlockMetrics: 'flex flex-wrap gap-3 text-sm text-muted-foreground',
  timeBlockActions: 'flex flex-wrap gap-2',
  finalHoursItem: 'flex flex-col gap-4 rounded-2xl bg-muted/45 px-4 py-4 md:flex-row md:items-center md:justify-between',
  finalHoursTitle: 'text-sm font-medium text-foreground',
  finalHoursCopy: 'mt-1 text-xs leading-5 text-muted-foreground',
  finalHoursActions: 'flex items-center gap-3',
  finalHoursValue: 'min-w-16 text-center text-sm font-semibold text-foreground',
  drawerFooter: 'flex flex-col gap-4 border-t border-border/60 pt-5 md:flex-row md:items-center md:justify-between',
  drawerSummary: 'grid gap-3 sm:grid-cols-2',
  drawerSummaryItem: 'grid gap-1 rounded-2xl bg-muted/45 px-4 py-3 text-sm text-muted-foreground',
};