export const todayPlannerOverviewStyles = {
  layout: 'grid gap-6 xl:grid-cols-[0.98fr_1.02fr]',
  stack: 'grid gap-6',
  summaryGrid: 'grid gap-4 sm:grid-cols-3',
  metricValue: 'text-3xl font-semibold tracking-tight text-foreground',
  planningMoment: 'text-xs uppercase tracking-[0.18em] text-muted-foreground',
  plannerList: 'grid gap-4',
  plannerItem: 'rounded-2xl bg-muted/45 px-4 py-4',
  plannerTop: 'flex items-start justify-between gap-4',
  plannerTitle: 'text-base font-medium text-foreground',
  plannerMeta: 'mt-1 text-sm leading-6 text-muted-foreground',
  plannerBadges: 'mt-4 flex flex-wrap gap-2',
  plannerBadge: 'inline-flex min-h-9 items-center rounded-full px-3 text-[11px] font-medium uppercase tracking-[0.16em]',
  plannerBadgeFixed: 'bg-slate-900 text-white',
  plannerBadgeRotative: 'bg-slate-200 text-slate-700',
  plannerHours: 'text-lg font-semibold text-foreground',
  sideStack: 'grid gap-6',
  projectLoadList: 'grid gap-3',
  projectLoadItem: 'flex items-center justify-between gap-3 rounded-2xl bg-background/75 px-4 py-3',
  projectLoadMeta: 'flex items-center gap-3',
  projectColor: 'h-3.5 w-3.5 rounded-full',
  projectName: 'text-sm font-medium text-foreground',
  projectCopy: 'text-xs text-muted-foreground',
};