export const loginWorkspaceStyles = {
  shell: 'relative min-h-screen overflow-hidden bg-[radial-gradient(circle_at_top_left,_rgba(14,116,144,0.18),_transparent_35%),radial-gradient(circle_at_bottom_right,_rgba(217,119,6,0.16),_transparent_32%),linear-gradient(180deg,_#f8fafc_0%,_#eef2f7_100%)] px-6 py-10 sm:px-8 lg:px-12',
  frame: 'mx-auto grid w-full max-w-7xl gap-8 lg:grid-cols-[1.1fr_0.9fr] lg:items-start',
  hero: 'relative overflow-hidden rounded-[2rem] border border-slate-200/70 bg-slate-950 px-8 py-10 text-slate-50 shadow-[0_32px_90px_-48px_rgba(15,23,42,0.72)]',
  heroGlow: 'pointer-events-none absolute inset-x-0 top-0 h-40 bg-[radial-gradient(circle_at_top,_rgba(34,211,238,0.22),_transparent_55%)]',
  heroCopy: 'relative max-w-2xl',
  eyebrow: 'text-[11px] font-semibold uppercase tracking-[0.22em] text-cyan-200/80',
  title: 'mt-4 text-4xl font-semibold tracking-tight text-white sm:text-5xl',
  description: 'mt-5 max-w-2xl text-sm leading-7 text-slate-300 sm:text-base',
  metrics: 'relative mt-10 grid gap-4 sm:grid-cols-3',
  metricCard: 'rounded-[1.5rem] border border-white/10 bg-white/5 p-5 backdrop-blur-sm',
  metricLabel: 'text-[11px] uppercase tracking-[0.2em] text-slate-400',
  metricValue: 'mt-3 text-lg font-semibold text-white',
  featureGrid: 'grid gap-4 sm:grid-cols-3',
  featureCard: 'rounded-[1.5rem] border border-border/60 bg-background/88 p-5 shadow-[0_20px_45px_-32px_rgba(15,23,42,0.34)] backdrop-blur',
  featureTitle: 'mt-4 text-base font-semibold tracking-tight text-foreground',
  featureDescription: 'mt-2 text-sm leading-6 text-muted-foreground',
  stack: 'grid gap-6',
  panelHeader: 'grid gap-4',
  accountList: 'grid gap-3',
  accountButton: 'w-full items-center justify-between gap-3 rounded-[1.25rem] border border-border/70 bg-background/90 px-4 py-4 text-left shadow-sm transition-colors hover:bg-muted/60',
  accountIdentity: 'grid gap-1',
  accountName: 'text-sm font-semibold text-foreground',
  accountEmail: 'text-xs text-muted-foreground',
  accountMeta: 'text-[11px] uppercase tracking-[0.16em] text-muted-foreground',
  actions: 'grid gap-3 sm:grid-cols-2',
  helperCard: 'rounded-[1.5rem] border border-dashed border-border/70 bg-background/75 p-5',
  helperTitle: 'text-sm font-semibold text-foreground',
  helperCopy: 'mt-2 text-sm leading-6 text-muted-foreground',
};