export const agendaWorkspaceStyles = {
  layout: 'grid gap-8 xl:grid-cols-[minmax(0,1fr)_22rem]',
  stack: 'grid gap-6',
  toolbar: 'flex flex-col gap-3 rounded-[1.6rem] border border-border/60 bg-card/85 p-4 shadow-[0_18px_55px_-30px_rgba(15,23,42,0.28)] md:flex-row md:items-center md:justify-between',
  toolbarGroup: 'flex flex-wrap items-center gap-3',
  dayLabel: 'text-sm font-semibold capitalize text-foreground',
  eventList: 'grid gap-4',
  eventCard: 'rounded-[1.5rem] border border-border/60 bg-card/90 p-5 shadow-[0_12px_48px_-24px_rgba(15,23,42,0.28)] backdrop-blur',
  eventHeader: 'flex flex-col gap-3 md:flex-row md:items-start md:justify-between',
  eventTitleBlock: 'grid gap-2',
  eventTitle: 'text-lg font-semibold tracking-tight text-foreground',
  eventMeta: 'flex flex-wrap items-center gap-2 text-sm text-muted-foreground',
  eventStatusBadge: 'rounded-full border border-border/70 bg-muted px-2.5 py-1 text-[11px] font-semibold uppercase tracking-[0.14em] text-muted-foreground',
  eventStatusBadgeDeclined: 'border-rose-200 bg-rose-50 text-rose-700',
  eventDot: 'h-2.5 w-2.5 rounded-full',
  eventBody: 'mt-4 grid gap-2 text-sm leading-6 text-foreground/88',
  eventLink: 'font-medium text-foreground underline underline-offset-4 transition hover:text-foreground/80',
  eventGuests: 'grid gap-2 rounded-2xl border border-border/50 bg-background/40 p-3',
  eventGuestList: 'grid gap-1 text-sm text-foreground/80',
  eventGuestItem: 'truncate',
  eventGuestOverflow: 'text-xs leading-5 text-muted-foreground',
  eventActions: 'mt-4 flex flex-wrap gap-3',
  summaryColumn: 'grid gap-4 self-start xl:sticky xl:top-28',
  summaryGrid: 'grid gap-4 sm:grid-cols-3 xl:grid-cols-1',
  metricValue: 'text-3xl font-semibold tracking-tight text-foreground',
  helper: 'text-xs leading-5 text-muted-foreground',
  compactList: 'grid gap-3 rounded-[1.5rem] border border-border/60 bg-card/85 p-5 shadow-[0_12px_48px_-24px_rgba(15,23,42,0.24)]',
  compactItem: 'flex items-center justify-between gap-3 rounded-2xl border border-border/60 bg-background/60 px-4 py-3',
  compactLabel: 'text-sm font-medium text-foreground',
  compactValue: 'text-sm text-muted-foreground',
};