export const authSettingsWorkspaceStyles = {
  container: 'mx-auto grid max-w-5xl gap-6',
  cardStack: 'grid gap-6 lg:grid-cols-[1fr_1fr]',
  profileList: 'grid gap-3',
  row: 'flex items-start justify-between gap-4 rounded-[1.25rem] border border-border/60 bg-background/80 px-4 py-4',
  label: 'text-[11px] font-semibold uppercase tracking-[0.18em] text-muted-foreground',
  value: 'mt-1 text-sm font-medium text-foreground',
  hint: 'text-sm leading-6 text-muted-foreground',
  connections: 'grid gap-3',
  accountCard: 'grid gap-4 rounded-[1.5rem] border border-border/60 bg-background/70 p-4',
  accountHeader: 'flex items-start justify-between gap-4',
  accountHeaderMeta: 'grid gap-1',
  accountStatus: 'text-xs font-medium text-muted-foreground',
  calendarsList: 'grid gap-3',
  calendarRow: 'flex flex-col gap-3 rounded-[1.25rem] border border-border/60 bg-background/90 px-4 py-4 sm:flex-row sm:items-start sm:justify-between',
  calendarMeta: 'grid gap-1',
  calendarNameRow: 'flex items-center gap-2',
  calendarDot: 'h-3 w-3 rounded-full border border-black/10',
  calendarTitle: 'text-sm font-semibold text-foreground',
  calendarBadge: 'rounded-full border border-border/80 bg-muted px-2 py-0.5 text-[10px] font-semibold uppercase tracking-[0.14em] text-muted-foreground',
  calendarAction: 'flex items-center gap-2 self-start sm:self-center',
};