export const taskFormStyles = {
  form: 'grid gap-5',
  grid: 'grid gap-4 md:grid-cols-2',
  field: 'grid gap-2',
  fieldWide: 'grid gap-2 md:col-span-2',
  label: 'text-sm font-medium text-foreground',
  input: 'min-h-11 rounded-2xl border border-border/70 bg-background px-4 text-sm text-foreground outline-none transition focus:border-foreground/40 focus:ring-2 focus:ring-ring/15',
  select: 'min-h-11 rounded-2xl border border-border/70 bg-background px-4 text-sm text-foreground outline-none transition focus:border-foreground/40 focus:ring-2 focus:ring-ring/15',
  textarea: 'min-h-[8rem] rounded-[1.5rem] border border-border/70 bg-background px-4 py-3 text-sm text-foreground outline-none transition focus:border-foreground/40 focus:ring-2 focus:ring-ring/15',
  preview: 'flex min-h-11 items-center rounded-2xl border border-border/70 bg-muted/35 px-4 text-sm font-medium text-foreground',
  checklistSection: 'grid gap-4 rounded-[1.5rem] border border-border/60 bg-background/40 p-4',
  checklistComposer: 'flex flex-col gap-3 md:flex-row',
  checklistList: 'grid gap-2',
  checklistEmpty: 'rounded-2xl border border-dashed border-border/70 bg-background/45 px-4 py-4 text-sm text-muted-foreground',
  checklistItem: 'flex items-center gap-3 rounded-2xl border border-border/60 bg-background px-3 py-3',
  checklistToggle: 'inline-flex h-9 w-9 shrink-0 items-center justify-center rounded-full border border-border/60 bg-muted/35 text-foreground/80 transition hover:text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring',
  checklistText: 'flex-1 text-sm text-foreground',
  helper: 'text-xs leading-5 text-muted-foreground',
  error: 'text-xs leading-5 text-rose-700',
  footer: 'flex flex-col gap-3 border-t border-border/60 pt-5 md:flex-row md:items-center md:justify-between',
  footerText: 'text-sm leading-6 text-muted-foreground',
  actions: 'flex flex-wrap gap-3',
};